export const author = {
  id: "123456",
  createdAt: String(Date.now()),
  bio: "Designer of Oasis",
  email: "alex@overstreet.me",
  name: "Alex Overstreet",
  username: "alex",
  photo: {
    url: "https://pbs.twimg.com/profile_images/1395178472549588992/zLCOzHj3_400x400.jpg",
    createdAt: String(Date.now()),
    id: "123456",
  },
};

export const data = [
  {
    id: "123456",
    author,
    commentCount: 0,
    comments: [],
    content: "Hey whats up",
    createdAt: String(Date.now()),
    votes: [],
    voteCount: 0,
    channel: "typescript",
  },
  {
    id: "123456",
    author,
    commentCount: 0,
    comments: [],
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt felis felis, at vestibulum risus fringilla vitae. Vivamus et est malesuada lectus posuere consequat nec eu dolor. Praesent eget condimentum urna, quis scelerisque justo. Praesent eget lorem venenatis, mattis massa ac, elementum erat.",
    createdAt: String(Date.now()),
    votes: [],
    voteCount: 0,
    channel: "typescript",
  },
  {
    id: "123456",
    author,
    commentCount: 0,
    comments: [],
    content: "Tsup is so fast. You should use it in all your projects",
    createdAt: String(Date.now()),
    votes: [],
    voteCount: 0,
    channel: "typescript",
  },
  {
    id: "123456",
    author,
    commentCount: 0,
    comments: [],
    content: "Nothing beats good ol javascript",
    createdAt: String(Date.now()),
    votes: [],
    voteCount: 0,
    channel: "javascript",
  },
  {
    id: "123456",
    author,
    commentCount: 0,
    comments: [],
    content: "I hate angular js",
    createdAt: String(Date.now()),
    votes: [],
    voteCount: 0,
    channel: "javascript",
  },
];
